version: '3.8'

services:
  web:
    build: ./shortener
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./shortener:/usr/src/app
    ports:
      - 8004:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - DATABASE_URL=postgresql://postgres:postgres@web-db:5432/shortener_dev
      - DATABASE_TEST_URL=postgresql://postgres:postgres@web-db:5432/shortener_test
    depends_on:
      - web-db

  web-db:
    build:
      context: ./shortener/setup_db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  client:
    build:
      context: ./client
    command: yarn start
    container_name: shortener-client
    depends_on:
      - web
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - ./client:/usr/src/app